# Site settings
title: The uberVU Dev blog
email: hello@ubervu.com
description: "Talking about our projects, technical solutions and how we overcome the challenges we face while building uberVU."
baseurl: ""
url: "http://ubervu.github.io/blog/"

# Build settings
markdown: kramdown
permalink: pretty
username: uberVU
ubervu: http://www.ubervu.com